[wechat]
key = 

[folder]
file = 

[keyword]
k1 = message:任务中断:"取消自动任务"
;k2 = level:INF;module:BetterGenshinImpact.GameTask.TaskRunner;message:→ "任务结束"
;k3 = level:ERR
;k4 = session:ChildSession:S4

[loop-time]
time = 300

[exe]
e1 = BetterGI.exe
e2 = YuanShen.exe

[log_offset]
